- src/Amadeus/Client/Session/Handler/SoapHeader2.php
- src/Amadeus/Client/Struct/HeaderV2/Session.php
Hi.
I tried to use develop branch to make some requests and faced with auth problems:
first:
PHP Fatal error:  SOAP-ERROR: Encoding: object has no 'SessionId' property in /path/to/amadeus-ws-client/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Session/Handler/Base.php on line 212
after fixing first one:
SOAPFAULT while sending message Fare_MasterPricerTravelBoardSearch:  12|Presentation|soap message header incorrect code: 0 at /path/to/amadeus-ws-client/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Session/Handler/Base.php line 212:
on any request.
After some investigations I figured out the problems. I made some changes which allows to run the code without errors.
P.S. Tests are ignores the problems, so my changes didn't influenced on its greens.
> Fix error with not well formed Auth header

- src/Amadeus/Client.php
- src/Amadeus/Client/Params/SessionHandlerParams.php
- src/Amadeus/Client/Session/Handler/Base.php
- src/Amadeus/Client/Session/Handler/HandlerInterface.php
- src/Amadeus/Client/Session/Handler/SoapHeader2.php
- src/Amadeus/Client/Session/Handler/SoapHeader4.php
- tests/Amadeus/Client/Params/SessionHandlerParamsTest.php
- tests/Amadeus/Client/ParamsTest.php
- tests/Amadeus/Client/Session/Handler/HandlerFactoryTest.php
- tests/Amadeus/Client/Session/Handler/SoapHeader2Test.php
- tests/Amadeus/Client/Session/Handler/SoapHeader4Test.php
- tests/Amadeus/Client/Session/Handler/testfiles/PNR_Reply_11_3_1A.xsd
- tests/Amadeus/Client/Session/Handler/testfiles/PNR_Retrieve_11_3_1A.xsd
- tests/Amadeus/Client/Session/Handler/testfiles/Security_SignOutReply_04_1_1A.xsd
- tests/Amadeus/Client/Session/Handler/testfiles/Security_SignOut_04_1_1A.xsd
- tests/Amadeus/Client/Session/Handler/testfiles/mediawsdl/AMA_MediaGetMediaRQ.xsd
- tests/Amadeus/Client/Session/Handler/testfiles/mediawsdl/AMA_MediaGetMediaRS.xsd
- tests/Amadeus/Client/Session/Handler/testfiles/mediawsdl/DUMMYWSAP_MediaServer.wsdl
- tests/Amadeus/Client/Session/Handler/testfiles/mediawsdl/DUMMYWSAP_MediaServer_invalid.wsdl
- tests/Amadeus/Client/Session/Handler/testfiles/mediawsdl/MediaServer_1.0.wsdl
- tests/Amadeus/Client/Session/Handler/testfiles/soapheader2/PNR_Reply_11_3_1A.xsd
- tests/Amadeus/Client/Session/Handler/testfiles/soapheader2/PNR_Retrieve_11_3_1A.xsd
- tests/Amadeus/Client/Session/Handler/testfiles/soapheader2/testwsdlsoapheader2.wsdl
As mentioned in #5 this PR adds support for handling multiple WSDL's in one WSAP (Profile, Media, ...).
Messages that use separate WSDL's are currently not yet supported, but can now be added without too much trouble.
> Support for multiple WSDL's

- docs/samples/masterpricertravelboard.rst
- src/Amadeus/Client/RequestOptions/Fare/MPFeeId.php
- src/Amadeus/Client/RequestOptions/FareMasterPricerTbSearch.php
- src/Amadeus/Client/Struct/Fare/MasterPricer/FareOptions.php
- src/Amadeus/Client/Struct/Fare/MasterPricer/FeeId.php
- src/Amadeus/Client/Struct/Fare/MasterPricerTravelBoardSearch.php
- tests/Amadeus/Client/Struct/Fare/MasterPricerTravelBoardSearchTest.php
Hey, I felt bad about just asking so I wanted to contribute a little bit.
Here is option to add FeeIds when searching in MasterPricer.
Possible options I saw in Amadeus.
```
FFI - shows fare family names from airlines (ex. Economy Saver)
UPH/UPB - upsell, so each recommendation gets reference to more expensive fares
```
Tell me if you want me to change anything! 
Cheers, Mike.
> Added fee ids to MasterPricer

- docs/samples/masterpricertravelboard.rst
- src/Amadeus/Client/RequestOptions/FareMasterPricerTbSearch.php
- src/Amadeus/Client/Struct/Fare/MasterPricer/CorporateId.php
- src/Amadeus/Client/Struct/Fare/MasterPricer/FareOptions.php
- src/Amadeus/Client/Struct/Fare/MasterPricerTravelBoardSearch.php
- tests/Amadeus/Client/Struct/Fare/MasterPricerTravelBoardSearchTest.php
Hey, fix for Master Pricer to support corporate pricing. 
I have no idea if it worked before, but I just checked with our access and Amadeus was raising an error that it is missing qualifier (also docs mention it)
> Bug with corporate Unifare pricing in Master Pricer

- src/Amadeus/Client/RequestCreator/Converter/PNR/RetrieveConv.php
- src/Amadeus/Client/Struct/Pnr/Retrieve.php
- tests/Amadeus/Client/RequestCreator/BaseTest.php
- tests/Amadeus/Client/Struct/Pnr/RetrieveTest.php
I tested it and it works, but it is not usable for me 😢  However code is there, so maybe someone else will need it.
Btw, for future Amadeus explorers:
- Airline <controlNumber> is created after you save PNR and close the session...
- Same thing with reservation company, it is filled with IATA code only after session is closed.
> Option to retrieve PNR that is active in context

- CHANGELOG.md
- docs/samples/masterpricertravelboard.rst
- src/Amadeus/Client/RequestOptions/Fare/MasterPricer/MultiTicketWeights.php
- src/Amadeus/Client/RequestOptions/MpBaseOptions.php
- src/Amadeus/Client/Struct/Fare/BaseMasterPricerMessage.php
- src/Amadeus/Client/Struct/Fare/MasterPricer/FareOptions.php
- src/Amadeus/Client/Struct/Fare/MasterPricer/NumberOfUnit.php
- src/Amadeus/Client/Struct/Fare/MasterPricer/PricingTicketing.php
- src/Amadeus/Client/Struct/Fare/MasterPricer/UnitNumberDetail.php
- src/Amadeus/Client/Struct/Fare/MasterPricerTravelBoardSearch.php
- src/Amadeus/Client/Struct/Ticket/CheckEligibility.php
- tests/Amadeus/Client/Struct/Fare/MasterPricerTravelBoardSearchTest.php
Added 2 options in MasterPricer:
- 5.56 Operation: 04.20 Fare Option - Multi-Ticket - Standard mode
- 5.57 Operation: 04.21 Fare Option - Multi-Ticket - Weighted mode
> Multi Ticket functionality implemented in MasterPricer messages

- src/Amadeus/Client.php
- src/Amadeus/Client/RequestCreator/Converter/Ticket/ProcessEDocConv.php
- src/Amadeus/Client/RequestOptions/TicketProcessEdoc.php
- src/Amadeus/Client/Struct/Ticket/EDoc/DocDetails.php
- src/Amadeus/Client/Struct/Ticket/EDoc/DocInfo.php
- src/Amadeus/Client/Struct/Ticket/EDoc/InfoGroup.php
- src/Amadeus/Client/Struct/Ticket/EDoc/MessageFunctionDetails.php
- src/Amadeus/Client/Struct/Ticket/EDoc/MsgActionDetails.php
- src/Amadeus/Client/Struct/Ticket/EDoc/ProcessEDoc.php
This just the main code to send Ticket_ProcessEdoc request and here's an examples of how to send this msg : 
```
use Amadeus\Client\RequestOptions\TicketProcessEdoc;
$data = new TicketProcessEdoc([
'ticketNumber'    =>'5125756077483',
'messageFunction' =>TicketProcessEdoc::ETKT
]);
$Eticket =  $client->ticketProcessEdoc($data);
```
> Ticket_processEdoc

- docs/samples/masterpricertravelboard.rst
- src/Amadeus/Client/RequestOptions/FareMasterPricerTbSearch.php
- src/Amadeus/Client/Struct/Fare/MasterPricer/TravelFlightInfo.php
- src/Amadeus/Client/Struct/Fare/MasterPricerTravelBoardSearch.php
- tests/Amadeus/Client/Struct/Fare/MasterPricerTravelBoardSearchTest.php
Added extra options for `Fare_MasterPricerTravelBoardSearch`.
From extranet:
> The user can request a maximum layover per connection (in hours and in minutes).
> Each connection of each requested segment has a layover limited to X hours and Y minutes.
> MPTB Search - added layover per connection options

- docs/samples.rst
In PnrAddMultiElementsOptions Itinerary option is declared as itineraries
> Fix Sample.rst

- docs/how-to.rst
> Fix errors in how-to documentation

- docs/about-get-started.rst
> commas missing

- docs/samples.rst
- src/Amadeus/Client/RequestOptions/Air/SellFromRecommendation/Segment.php
- src/Amadeus/Client/Struct/Air/FlightDate.php
- src/Amadeus/Client/Struct/Air/SegmentInformation.php
- src/Amadeus/Client/Struct/Air/TravelProductInformation.php
- tests/Amadeus/Client/Struct/Air/SellFromRecommendationTest.php
Even though is not mandatory it may help with flights that are overnight.
> Implemented attaching arrival date and time at Air_SellFromRecommendation

- src/Amadeus/Client/Struct/Fop/MopDescription.php
Fop sequence number check must be changed, because `empty()` method returns `false`, when `$sequenceNr = 0`.
It breaks the struct when trying to add a form of payment (FP) element including both old and new forms of payment where old must have 0 sequence number 
(First example on FOP_CreateFormOfPayment examples page at extranet)
```
<fopSequenceNumber>
<sequenceDetails>
<number>0</number>
</sequenceDetails>
</fopSequenceNumber>
```
> FOP_CreateFormOfPayment allow sequence number 0

- docs/list-of-supported-messages.rst
- src/Amadeus/Client.php
- src/Amadeus/Client/RequestCreator/Converter/PNR/IgnoreConv.php
- src/Amadeus/Client/RequestOptions/PnrIgnoreOptions.php
- src/Amadeus/Client/ResponseHandler/PNR/HandlerIgnore.php
- src/Amadeus/Client/Struct/Pnr/Ignore.php
- src/Amadeus/Client/Struct/Pnr/Ignore/ClearInformation.php
- tests/Amadeus/Client/Struct/Pnr/IgnoreTest.php
- tests/Amadeus/ClientTest.php
We implementing the PNR_Ignore Call to use it in certain Webservices in combination with transactions/sessions. Actually it is not possible to ignore an PNR in a single call but this is needed and also usefull for some workflows.
What we have done:
* implementing PNR_Ignore into existing client structure including RequestOptions, RequestCreator, ResponseHandler and Struct classes
* adding tests for the client call and the struct class
* add PNR_Ignore to the list of supported messages
> Implementing PNR_Ignore

- tests/Amadeus/Client/Struct/Air/RetrieveSeatMapTest.php
This test makes covered `Struct` folder to 100%.
Not covered to 100% only `Client\SoapClient.php`
> Added RetrieveSeatMap/Reservation test

- src/Amadeus/Client/Session/Handler/SoapHeader4.php
- src/Amadeus/Client/Struct/Security/PasswordInfo.php
I know that is not urgent at all, but I had some free time and desire to fix it. #151 
Personally I am a little confused with `if` statement that will check message name on every call, but maybe I'm too worried.
In any case, maybe @DerMika  have any idea of how this could be solved in other way?
> Fix double authentication when calling Security_Authenticate with SoapHeader 4

- docs/samples/masterpricertravelboard.rst
- src/Amadeus/Client/RequestOptions/Fare/MPDate.php
- src/Amadeus/Client/RequestOptions/Fare/MPTripDetails.php
- src/Amadeus/Client/Struct/Fare/MasterPricer/TimeDetails.php
- src/Amadeus/Client/Struct/Fare/MasterPricer/TripDetails.php
- tests/Amadeus/Client/Struct/Fare/MasterPricer/TripDetailsTest.php
- tests/Amadeus/Client/Struct/Fare/MasterPricerCalendarTest.php
Enhancement for MasterPricerCalendar message.
Resolves #259 
**WIP** - Need to test manually, that XML are generating as expected:
```
<timeDetails>
<tripDetails>
<flexibilityQualifier>C</flexibilityQualifier>
<tripInterval>1</tripInterval>
<tripDuration>7</tripDuration>
</tripDetails>
</timeDetails>
```
I'll test soon and update PR.
UPD: Message XML generated correctly, but I get error response from Amadeus with message "Invalid trip duration option". I guess it depends on office settings, but I ask Amadeus Support and wait for their reply.
UPD2: Amadeus currently not uses this node, but may be used in future versions.
> MasterPricer trip details

- src/Amadeus/Client/Session/Handler/SoapHeader4.php
- tests/Amadeus/Client/Session/Handler/SoapHeader4Test.php
- tests/Amadeus/Client/Session/Handler/testfiles/Security_AuthenticateReply_06_1_1A.xsd
- tests/Amadeus/Client/Session/Handler/testfiles/Security_Authenticate_06_1_1A.xsd
- tests/Amadeus/Client/Session/Handler/testfiles/testwsdl.wsdl
With commit https://github.com/amabnl/amadeus-ws-client/commit/b420d436ac9577ee864f042ec10566eba860418b there was a bug introduced for stateful *Security_Authenticate* requests.
Those requests always have their *TransactionStatusCode* set to "InSeries" where it should be "Start".
Amadeus webservices will respond with a 
`<faultstring>12|Presentation|soap message header incorrect</faultstring>` in this case.
> Fixing wrong TransactionStatusCode while using stateful Security_Authenticate requests with SoapHeader4

- docs/samples/masterpricertravelboard.rst
- src/Amadeus/Client/RequestOptions/Fare/MasterPricer/FormOfPaymentDetails.php
- src/Amadeus/Client/RequestOptions/MpBaseOptions.php
- src/Amadeus/Client/Struct/Fare/BaseMasterPricerMessage.php
- src/Amadeus/Client/Struct/Fare/MasterPricer/FareOptions.php
- src/Amadeus/Client/Struct/Fare/MasterPricer/FormOfPaymentDetails.php
- tests/Amadeus/Client/Struct/Fare/MasterPricer/FormOfPaymentDetailsTest.php
- tests/Amadeus/Client/Struct/Fare/MasterPricerTravelBoardSearchTest.php
Implementation of `formOfPayment` option for _MasterPricer_ messages.
Request message generates correctly, Amadeus returns search results. Tested in PDT.
Resolves #273
> Master Pricer: Form of Payment

- docs/samples/pnr-create-modify.rst
there is no attribute `PAXTYPE_PASSENGER` in TourCode class.
> update example to work with tour code

- src/Amadeus/Client/Session/Handler/Base.php
- src/Amadeus/Client/Util/MsgBodyExtractor.php
- tests/Amadeus/Client/Session/Handler/SoapHeader2Test.php
- tests/Amadeus/Client/Session/Handler/SoapHeader4Test.php
- tests/Amadeus/Client/Util/MsgBodyExtractorTest.php
Resolves #302 
Also using substrings handles whole XML string faster than with `preg_match`. For few milliseconds less, but anyway :)
> Extractor refactoring

- src/Amadeus/Client/Session/Handler/Base.php
This should fix #429 . When catching the SoapFault, the post-message session check did not occur.
> fix for #429: no session after PNR Retrieve failed

- docs/samples/masterpricertravelboard.rst
- src/Amadeus/Client/RequestOptions/Fare/MPPassenger.php
- src/Amadeus/Client/Struct/Fare/MasterPricer/PaxReference.php
- tests/Amadeus/Client/Struct/Fare/MasterPricerTravelBoardSearchTest.php
Need an ability to define several pax types at once:
```xml
<ns1:paxReference>
<ns1:ptc>ADT</ns1:ptc>
<ns1:ptc>IIT</ns1:ptc>
<ns1:traveller>
<ns1:ref>1</ns1:ref>
</ns1:traveller>
<ns1:traveller>
<ns1:ref>2</ns1:ref>
</ns1:traveller>
</ns1:paxReference>
```
Tested with PRD env.
> Add support for multiple pax types in MasterPricerTravelBoard

- CHANGELOG.md
- docs/samples/fop-createfop.rst
- src/Amadeus/Client/RequestOptions/Fop/CreditCardInfo.php
- src/Amadeus/Client/RequestOptions/Fop/CreditCardSupplementaryData.php
- src/Amadeus/Client/RequestOptions/Fop/MopInfo.php
- src/Amadeus/Client/RequestOptions/Fop/ThreeDSecureInfo.php
- src/Amadeus/Client/Struct/Fop/AuthenticationData.php
- src/Amadeus/Client/Struct/Fop/AuthenticationDataDetails.php
- src/Amadeus/Client/Struct/Fop/CardSupplementaryCriteriaDetails.php
- src/Amadeus/Client/Struct/Fop/CardSupplementaryData.php
- src/Amadeus/Client/Struct/Fop/CreateFormOfPayment/GroupUsage14.php
- src/Amadeus/Client/Struct/Fop/CreditCardDetailedData.php
- src/Amadeus/Client/Struct/Fop/GroupUsage.php
- src/Amadeus/Client/Struct/Fop/MopDescription.php
- src/Amadeus/Client/Struct/Fop/PaymentModule.php
- src/Amadeus/Client/Struct/Fop/TdsInformation.php
- tests/Amadeus/Client/Struct/Fop/CreateFormOfPaymentTest.php
- tests/Amadeus/Client/Struct/Fop/MopDescriptionTest.php
- tests/Amadeus/Client/Struct/Fop/TdsInformationTest.php
Add 3DS v2 support with external authentication in FOP_CreateFormOfPayment during  Light Ticketing Scope
Light Ticketing implementation guide - Dec 2022 (DOCX)
On Create Form Of Payment Documentation Page
https://developers.amadeus.com/functional-doc/1379
> add 3DS v2.0 params with external authentication in FOP

- composer.json
- composer.lock
This PR updates the composer.lock file to fix an issue generated by #475 when installing the package directly from ``amabnl/amadeus-ws-client`` despite the change in composer.json
It also removes the platform php locking strategy to allow higher versions of php since it is already required in the "required" section of composer.json.
@DerMika
> Update composer.lock file still locking psr/log to 1.0.0

- src/Amadeus/Client/Session/Handler/SoapHeader4.php
So, after fix from https://github.com/amabnl/amadeus-ws-client/pull/449
The argument passed to `mt_srand`: `(int) microtime() * 10000` is always equal 0:
That's because when cast `microtime()` string to `(int)` it gives 0:
```php
> (int) microtime()
= 0
```
> Fix SoapHeader4::generateGuid() has mt_srand() argument always equal 0 after https://github.com/amabnl/amadeus-ws-client/pull/449
